server {
    listen 3000;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location ^~ /api/ {
        proxy_pass http://blog-backend:8080;
    }

    location = /admin {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/articlemgmt {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/commentmgmt {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/momentsmgmt {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/content {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/writearticle {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location ^~ /admin/article/edit/ {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/writemoment {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/categorisemgmt {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/tagsmgmt {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/forum-entry {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /admin/site {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location ^~ /admin/dashboard/ {
        proxy_pass http://blog-backend:8080;
    }

    location = /admin/categories {
        proxy_pass http://blog-backend:8080;
    }

    location ^~ /admin/categories/ {
        proxy_pass http://blog-backend:8080;
    }

    location = /admin/tags {
        proxy_pass http://blog-backend:8080;
    }

    location ^~ /admin/tags/ {
        proxy_pass http://blog-backend:8080;
    }

    location = /admin/articles {
        proxy_pass http://blog-backend:8080;
    }

    location ^~ /admin/articles/ {
        proxy_pass http://blog-backend:8080;
    }

    location = /admin/comments {
        proxy_pass http://blog-backend:8080;
    }

    location ^~ /admin/comments/ {
        proxy_pass http://blog-backend:8080;
    }

    location = /admin/moment {
        proxy_pass http://blog-backend:8080;
    }

    location ^~ /admin/moment/ {
        proxy_pass http://blog-backend:8080;
    }

    location ^~ /admin/upload/ {
        proxy_pass http://blog-backend:8080;
    }

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
